export const STORE_COVER_IMAGE_FILE_MAX_SIZE = "8MB";
export const STORE_COVER_IMAGE_FILE_MAX_SIZE_BYTES = 1024 * 1024 * 8; // 10MB

export const STORE_AVATAR_IMAGE_FILE_MAX_SIZE = "4MB";
export const STORE_AVATAR_IMAGE_FILE_MAX_SIZE_BYTES = 1024 * 1024 * 4; // 4MB
